import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";

// 确保 dist 目录存在
fs.mkdirSync("dist", { recursive: true });

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "dist/main.js",
});

if (prod) {
  await context.rebuild();

  // 构建完成后，把 manifest.json 和 styles.css 一并复制到 dist/
  fs.copyFileSync("manifest.json", "dist/manifest.json");
  fs.copyFileSync("src/styles.css", "dist/styles.css");
  console.log("✅ 构建完成，产物在 dist/ 目录");

  process.exit(0);
} else {
  // 开发模式：监听变化时也同步静态文件
  fs.copyFileSync("manifest.json", "dist/manifest.json");
  fs.copyFileSync("src/styles.css", "dist/styles.css");
  console.log("👀 开发模式启动，监听文件变化...");
  await context.watch();
}
